---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'
# set AD datas ==================================================================================================

- name: RDP host
  hosts: rdp
  roles:
  - { role: 'rdp', tags: 'rdp'}

